# Generated by Django 4.2.24 on 2025-09-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_options_alter_author_slug_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(default='España', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='España', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='Jonh', max_length=100),
            preserve_default=False,
        ),
    ]
