# Generated by Django 4.2.24 on 2025-10-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_bookreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
