# Generated by Django 4.2.24 on 2025-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_author_created_at_book_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('stock__gte', 0)), name='book_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bookreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'book'), name='unique_active_reservation_per_user_book'),
        ),
    ]
